// fintrackpro-backend/utility/mockTransactions.js

module.exports.mockTransactions = [
  // 1. Credit Card transactions (HDFC)
  {
    date: "2025-08-02",
    category: "Cash Withdrawal",
    type: "credit",
    amount: 10000,
    userShare: 10000,
    paymentMode: "Card",
    shared: false,
    people: 1,
    description: "Cash withdrawal on 2 Aug",
    isCredit: true,
  },
  {
    date: "2025-08-01",
    category: "Borrowed",
    type: "credit",
    amount: 5000,
    userShare: 5000,
    paymentMode: "Card",
    shared: true,
    people: 1,
    description: "Drajju borrowed within 1–16 Aug",
    isCredit: true,
  },
  {
    date: "2025-08-14",
    category: "Borrowed",
    type: "credit",
    amount: 13050,
    userShare: 13050,
    paymentMode: "Card",
    shared: true,
    people: 1,
    description: "Rakesh borrowed",
    isCredit: true,
  },
  {
    date: "2025-08-14",
    category: "Borrowed",
    type: "credit",
    amount: 3200,
    userShare: 3200,
    paymentMode: "Card",
    shared: true,
    people: 1,
    description: "Arun borrowed",
    isCredit: true,
  },
  {
    date: "2025-08-14",
    category: "Borrowed",
    type: "credit",
    amount: 12000,
    userShare: 12000,
    paymentMode: "Card",
    shared: true,
    people: 1,
    description: "Hari borrowed",
    isCredit: true,
  },
  {
    date: "2025-08-14",
    category: "Cash Withdrawal",
    type: "credit",
    amount: 3000,
    userShare: 3000,
    paymentMode: "Card",
    shared: false,
    people: 1,
    description: "Additional cash withdrawal by you",
    isCredit: true,
  },
  {
    date: "2025-08-14",
    category: "Entertainment",
    type: "credit",
    amount: 890,
    userShare: 890,
    paymentMode: "Card",
    shared: false,
    people: 1,
    description: "BookMyShow ticket",
    isCredit: true,
  },
  {
    date: "2025-08-14",
    category: "Entertainment",
    type: "credit",
    amount: 170,
    userShare: 170,
    paymentMode: "Card",
    shared: false,
    people: 1,
    description: "BookMyShow ticket",
    isCredit: true,
  },

  // 2. Normal income & transfers
  {
    date: "2025-08-05",
    category: "Salary",
    type: "income",
    amount: 28000,
    userShare: 28000,
    paymentMode: "Bank",
    shared: false,
    people: 1,
    description: "Monthly income",
    isCredit: false,
  },
  {
    date: "2025-08-06",
    category: "Family",
    type: "expense",
    amount: 5000,
    userShare: 5000,
    paymentMode: "Bank",
    shared: false,
    people: 1,
    description: "Money sent to home",
    isCredit: false,
  },
  {
    date: "2025-08-07",
    category: "Rent",
    type: "expense",
    amount: 7000,
    userShare: 7000,
    paymentMode: "Bank",
    shared: false,
    people: 1,
    description: "Hostel rent",
    isCredit: false,
  },

  // 3. Normal daily spending examples
  {
    date: "2025-08-01",
    category: "Food",
    type: "expense",
    amount: 450,
    userShare: 450,
    paymentMode: "Cash",
    shared: false,
    people: 1,
    description: "Groceries at supermarket",
    isCredit: false,
  },
  {
    date: "2025-08-03",
    category: "Transport",
    type: "expense",
    amount: 120,
    userShare: 120,
    paymentMode: "UPI",
    shared: false,
    people: 1,
    description: "Uber ride",
    isCredit: false,
  },
  {
    date: "2025-08-04",
    category: "Entertainment",
    type: "expense",
    amount: 800,
    userShare: 800,
    paymentMode: "Cash",
    shared: false,
    people: 1,
    description: "Movie tickets (paid normally)",
    isCredit: false,
  },
];
